version: "3.1"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "user"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306
    volumes:
      - dbv:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 7780:80
    environment:
      - PMA_ARBITRARY=1
  fakesmtp:
    image: gessnerfl/fake-smtp-server:1.10.4
    restart: unless-stopped
    environment:
      - FAKESMTP_PORT=5025
      - FAKESMTP_FORWARDEMAILS=false
      - FAKESMTP_AUTHENTICATION_USERNAME=username
      - FAKESMTP_AUTHENTICATION_PASSWORD=password
      - SERVER_PORT=5080
    ports:
      - 7025:5025
      - 7082:5080
volumes:
  dbv:
